apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: deepstorage
  project: default
  source:
    repoURL: 'https://charts.min.io/'
    targetRevision: 5.0.3
    helm:
      values: |-
        existingSecret: minio-secrets
        replicas: 3
        persistence:
          size: 20Gi
        service:
          type: LoadBalancer
        consoleService:
          type: LoadBalancer
        resources:
          requests:
            memory: 1Gi
    chart: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
