apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    name: microk8s
    namespace: deepstorage
  project: default
  source:
    repoURL: 'https://charts.min.io/'
    path: repository/helm-charts/minio
    targetRevision: 4.0.15
    helm:
      values: |-
        persistence:
          size: 10Gi
        replicas: 2
        gateway:
          replicas: 2
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
    chart: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
