apiVersion: batch/v1
kind: CronJob
metadata:
  name: crj-strimzi-events
  namespace: app
spec:
  schedule: "0 0 */1 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-strimzi-events
            image: owshq/ingestion-data-stores:0.1
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: cronjob-environment
            command: ["/bin/sh", "-c"]
            args:
              - echo starting;
                python3.9 cli.py 'strimzi-users-json';
                python3.9 cli.py 'strimzi-rides-json';
                python3.9 cli.py 'strimzi-users-avro';
                python3.9 cli.py 'strimzi-credit-card-json';
                python3.9 cli.py 'strimzi-agent-avro';
                python3.9 cli.py 'strimzi-musics-avro';
                python3.9 cli.py 'strimzi-rides-avro';
                python3.9 cli.py 'strimzi-movies-titles-json';
                python3.9 cli.py 'strimzi-musics-avro';
                echo done;
          restartPolicy: OnFailure