apiVersion: batch/v1
kind: CronJob
metadata:
  name: crj-mongodb-ingestion
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-mongodb-ingestion
            image: owshq/ingestion-data-stores:0.1
            imagePullPolicy: IfNotPresent
            command: ["python3.9","cli.py","mongodb"]
          restartPolicy: OnFailure
