apiVersion: batch/v1
kind: CronJob
metadata:
  name: crj-mysql-ingestion
  namespace: app
spec:
  schedule: "0 0 */1 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-mysql-ingestion
            image: ingestion-data-stores:0.1
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: cronjob-environment
            command: ["python3.9","cli.py","mysql"]
          restartPolicy: OnFailure


