apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crj-minio-ingestion
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-minio-ingestion
            image: owshq/ingestion-data-stores:0.1
            imagePullPolicy: IfNotPresent
            command: ["python3.9","cli.py","minio"]
          restartPolicy: OnFailure

