apiVersion: batch/v1
kind: CronJob
metadata:
  name: crj-ysql-ingestion
  namespace: app
spec:
  schedule: "0 0 */1 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-ysql-ingestion
            image: gersonrs/ingestion-data-stores:0.1
            imagePullPolicy: IfNotPresent
            command: ["python3.9","cli.py","ysql"]
          restartPolicy: OnFailure


