apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    name: microk8s
    namespace: orchestrator
  project: default
  source:
    repoURL: 'https://airflow.apache.org/'
    targetRevision: 1.7.0
    helm:
      values: |-
        executor: "KubernetesExecutor"
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
        # webserver:
        #   service: 
        #     type: LoadBalancer
        #     loadBalancerIP: 192.168.0.203
        data:
          metadataConnection:
            user: gerson
            pass: '12345678'
            protocol: postgresql
            host: postgres-postgresql.database.svc.cluster.local
            port: 5432
            db: potato
            sslmode: disable
        postgresql:
          enabled: false
        dags:
          gitSync:
            enabled: true
            repo: "git@github.com:GersonRS/airflow-dags.git"
            branch: main
            rev: HEAD
            depth: 1
            maxFailures: 1
            subPath: "dags"
            sshKeySecret: airflow-ssh-secret
            knownHosts: |-
              |1|yutcXh9HhbK6KCouq3xMQ38B9ns=|V9zQ39gzVxSZ75WU78CGJiVKCOk= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
              |1|7ww9iNXn8d1jtXlaDjt+fYpsRi0=|vfHsTzw+QATWkCKD7kgG2jhu/1w= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        extraSecrets:
          airflow-ssh-secret:
            data: |
              gitSshKey: 'LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCbTdGZ3gwdEI3RVE5TXVEeS94S3hYbW01RWdFc1NUMnMydXhlTzViSHo5UUFBQUppQW1scVFnSnBhCmtBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQm03Rmd4MHRCN0VROU11RHkveEt4WG1tNUVnRXNTVDJzMnV4ZU81Ykh6OVEKQUFBRUFSY3BTVkJ5aFQyUkkyKzZDSmVsWFJ2NkJJR0lhWExWbDNvZGhtOFdnWkxtYnNXREhTMEhzUkQweTRQTC9FckZlYQpia1NBU3hKUGF6YTdGNDdsc2ZQMUFBQUFFV2RsY25OdmJuSnpRR3hwZG1VdVkyOXRBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K'
        
    chart: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
