apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: airflow
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/apache/airflow'
    path: chart
    targetRevision: HEAD
    helm:
      values: |-
        executor: "KubernetesExecutor"
        workers:
          persistence:
            size: 10Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: orchestrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
