apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    name: microk8s
    namespace: orchestrator
  project: default
  source:
    repoURL: 'https://airflow.apache.org/'
    targetRevision: 1.7.0
    helm:
      values: |-
        executor: "KubernetesExecutor"
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
        data:
          metadataConnection:
            user: gerson
            pass: '12345678'
            protocol: postgresql
            host: postgres-postgresql.database.svc.cluster.local
            port: 5432
            db: potato
            sslmode: disable
        postgresql:
          enabled: false
    chart: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
