apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: airflow
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://airflow.apache.org/'
    targetRevision: 1.7.0
    helm:
      values: |-
        executor: "KubernetesExecutor"
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
        data:
          metadataConnection:
            user: admin
            pass: Q1NQZRd1GO
            protocol: postgresql
            host: postgres-postgresql.database.svc.cluster.local
            port: 5432
            db: potato
            sslmode: disable
        postgresql:
          enabled: false
    chart: airflow
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: orchestrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
