apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    name: microk8s
    namespace: database
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 11.9.11
    helm:
      values: |-
        global:
          postgresql:
            auth:
              username: "gerson"
              password: "12345678"
              database: "potato"
            service:
              ports:
                postgresql: "5432"
        image:
          debug: true
        primary:
          configuration: |-
            huge_pages = 'off'
            listen_addresses = '*'
            port = '5432'
            max_wal_size = '16000MB'
            min_wal_size = '4000MB'
          extraVolumeMounts:
            - name: pg-sample-config
              mountPath: /opt/bitnami/postgresql/share/postgresql.conf.sample
              subPath: postgresql.conf.sample
          extraVolumes:
            - configMap:
                name: pg-sample-config
              name:  pg-sample-config
        extraDeploy:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: pg-sample-config
            data:
              postgresql.conf.sample: |-
                huge_pages = 'off'
    chart: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
