apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yugabytedb
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    name: microk8s
    namespace: database
  project: default
  source:
    repoURL: 'https://charts.yugabyte.com'
    targetRevision: 2.15.2
    helm:
      values: |-
        preflight:
          skipUlimit: true
        storage:
          master:
            count: 1
            size: 10Gi
            storageClass: openebs-hostpath
          tserver:
            count: 1
            size: 10Gi
            storageClass: openebs-hostpath
        resource:
          master:
            requests:
              cpu: 500m
              memory: 0.5Gi
            limits:
              cpu: 1
              memory: 1Gi
          tserver:
            requests:
              cpu: 500m
              memory: 0.5Gi
            limits:
              cpu: 1
              memory: 1Gi
        replicas:
          master: 1
          tserver: 1
    chart: yugabyte
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
