apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: edh
spec:
  kafka:
    version: 3.2.3
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 500Mi
        cpu: "250m"
      limits:
        memory: 1Gi
        cpu: "500m"  
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    replicas: 1
    storage:
      type: ephemeral
    resources:
      # requests and limits
      requests:
        memory: 256Mi
        cpu: "250m"
      limits:
        memory: 512Mi
        cpu: "500m"  
  entityOperator:
    topicOperator: {}
    userOperator: {}