{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ include "fullname" . }}-claim
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "lenses"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    lenses.io/app: {{ template "name" . }}
    lenses.io/app.type: lenses-volume-claim
spec:
  accessModes:
{{ toYaml .Values.persistence.accessModes | indent 4 }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
{{- end -}}