apiVersion: v1
kind: Service
metadata:
  name: svc-lb-schema-registry
  namespace: ingestion
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: cp-schema-registry