apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: lenses
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://bitbucket.org/owshq/trn-mst-bg-k8s.git'
    path: repository/helm-charts/lenses
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dataops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
