apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  project: default
  source:
    repoURL: 'https://strimzi.io/charts/'
    targetRevision: 0.32.0
    helm:
      values: |-
        replicas: 2
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
    chart: strimzi-kafka-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
