apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'git@github.com:GersonRS/big-data-on-k8s.git'
    path: repository/helm-charts/kube-prometheus-stack
    targetRevision: HEAD
    helm:
      skipCrds: true
      values: |-
        grafana:
          adminPassword: 12345678
  syncPolicy:
    automated:
      prune: true
      selfHeal: true