apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: load-balancers-svc
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'git@github.com:GersonRS/big-data-on-k8s.git'
    path: repository/svc-lbs/
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
