{{- /*
  Ref - https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-services#registering_a_service_for_export
*/}}
{{- if .Values.multicluster.createServiceExports }}
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: {{ .Values.oldNamingStyle | ternary "yb-masters" (printf "%s-%s" (include "yugabyte.fullname" .) "yb-masters") | quote }}
  namespace: "{{ .Release.Namespace }}"
  labels:
  {{- include "yugabyte.labels" . | indent 4 }}
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: {{ .Values.oldNamingStyle | ternary "yb-tservers" (printf "%s-%s" (include "yugabyte.fullname" .) "yb-tservers") | quote }}
  namespace: "{{ .Release.Namespace }}"
  labels:
  {{- include "yugabyte.labels" . | indent 4 }}
{{ end -}}