apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: src-app-users-json
  labels:
    strimzi.io/cluster: edh
spec:
  partitions: 9
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824