apiVersion: v1
kind: Service
metadata:
  name: svc-lb-ingestion-data-stores-python-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: ingestion-data-stores-python-app



